# Generated by Django 2.1.7 on 2019-02-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studying', '0002_tftask_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default=None, max_length=50)),
                ('choice', models.CharField(default=None, max_length=50)),
                ('points', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WordBoxTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('without_wordbox', models.BooleanField(default=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_boxes', to='studying.Testing')),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='match_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='studying.WordBoxTask'),
        ),
    ]
