# Generated by Django 2.1.7 on 2019-02-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying', '0003_auto_20190220_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordboxtask',
            name='without_wordbox',
            field=models.BooleanField(default=False),
        ),
    ]
